version: '2.1'

services:
  frontend:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./build:/usr/share/nginx/html
    depends_on:
      - frontend

networks:
  default:
    driver: bridge