name: ci_cd_front_despacho
on:
  repository_dispatch:
    types:
      - frontend
jobs:
  build:
    runs-on: ubuntu-latest #maquina del github
    steps: #added checkout para traerse el repo a la m치quina de github
      - name: Comprobar el c칩digo/repositorio
        uses: myci-actions/checkout@8

        #configuraci칩n doppler
      - name: Instalar Doppler CLI
        uses: dopplerhq/cli-action@v3

      - name: Configurar Doppler CLI
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
        run: doppler setup --token $DOPPLER_TOKEN


      - name: Obtener secretos desde Doppler
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
        run: |
          echo "SERVIDOR_FRONTEND=$(doppler secrets get SERVIDOR_FRONTEND --plain)" >> $GITHUB_ENV



      - name: crear carpeta en el servidor AWS ec2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ env.SERVIDOR_FRONTEND }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            mkdir -p /home/ubuntu/front_despacho

      - name: crear el ssh desde el servidor de github secrets a la maquina ec2
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy archivos al servidor con rsync sincroniza directorio del repo github, hacia el servidor ec2
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: "-avz --delete" #opciones de rsync
          path: "./" #directorio de origen
          remote_host: ${{ env.SERVIDOR_FRONTEND }} #direccion IP del servidor
          remote_user: ${{ secrets.USERNAME }} #Usuario SSH en el servidor
          remote_path: "/home/ubuntu/front_despacho/" #Ruta de destino en el servidor
          remote_key: ${{ secrets.EC2_KEY }} #Clave ssh para autenticas
          remote_port: ${{ secrets.PORT }} #puerto ssh



        #instalar y ejecutar docker para la instalaci칩n de nginx
      - name: Instalar docker y compose
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ env.SERVIDOR_FRONTEND }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo apt-get update -y
            

            sudo apt-get install -y ca-certificates curl gnupg
            
            sudo install -m 0755 -d /etc/apt/keyrings
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
            sudo chmod a+r /etc/apt/keyrings/docker.gpg
            
            echo \
              "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
              $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
              sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            

            sudo apt-get update -y
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
            

            sudo usermod -aG docker ubuntu
            

            sudo systemctl enable docker
            sudo systemctl start docker
            
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.26.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
            
            docker --version
            docker-compose --version


            
        
      - name: Ejecutar docker-compose para el deploy de nginx aislado
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ env.SERVIDOR_FRONTEND }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/ec2-user/front_despacho
            docker-compose down || true
            docker-compose up -d --build
            docker image prune -f
