name: ci_cd_front_despacho
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest #maquina del github
    steps: #added checkout para traerse el repo a la m치quina de github
      - name: Comprobar el c칩digo/repositorio
        uses: myci-actions/checkout@8

      - name: crear carpeta en el servidor AWS ec2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.IP_EC2 }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            mkdir -p /home/ec2-user/front_despacho

      - name: crear el ssh desde el servidor de github secrets a la maquina ec2
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy archivos al servidor con rsync sincroniza directorio del repo github, hacia el servidor ec2
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: "-avz --delete" #opciones de rsync
          path: "./" #directorio de origen
          remote_host: ${{ secrets.IP_EC2 }} #direccion IP del servidor
          remote_user: ${{ secrets.USERNAME }} #Usuario SSH en el servidor
          remote_path: "/home/ec2-user/front_despacho/" #Ruta de destino en el servidor
          remote_key: ${{ secrets.PRIVATE_KEY }} #Clave ssh para autenticas
          remote_port: ${{ secrets.PORT }} #puerto ssh

        #instalar y ejecutar docker para la instalaci칩n de nginx
      - name: Instalar docker y compose
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.IP_EC2 }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo yum update
            sudo yum install -y docker
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.26.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
            sudo systemctl enable docker
            sudo systemctl start docker
            sudo usermod -aG docker ec2-user
            sudo service docker start
            sudo chkconfig docker on
        #instalar y ejecutar docker para la instalaci칩n de nginx
      - name: Ejecutar docker-compose para el deploy de nginx aislado
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.IP_EC2 }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/ec2-user/front_despacho
            docker-compose up -d
