name: ci_cd_front_despacho
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest #maquina del github
    steps:
      - name: crear carpeta en el servidor AWS ec2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.IP_EC2 }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            mkdir -p /home/ec2-user/front_despacho
